services:
  api:
    build:
      context: ./apis/typescript # Change the api language for a different api language
      dockerfile: Dockerfile
    container_name: api
    environment:
      PORT: 4022
      NODE_ENV: "production"
      AUTH_TOKEN: "2sOm7HFC5Yg6VaNb"

      MINIO_ENDPOINT: "minio"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "password123"
    ports:
      - "4022:4022"
    depends_on:
      - minio
    networks:
      - minio-net

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000"
      - "9001"
    networks:
      - minio-net

  nginx:
    build:
      context: ./ssl
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - ./ssl/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/nginx/certs:/etc/nginx/certs
    ports:
      - "443:443"
    depends_on:
      - minio
    networks:
      - minio-net

volumes:
  minio_data:

networks:
  minio-net:
