services:
  api:
    build:
      context: ./apis/typescript # Change the api language for a different api language
      dockerfile: Dockerfile
    container_name: api
    environment:
      PORT: 4022
      NODE_ENV: "production"
      AUTH_TOKEN: "2sOm7HFC5Yg6VaNb"

      MINIO_ENDPOINT: "minio"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "password123"
    ports:
      - "4022:4022"
    depends_on:
      - minio
    networks:
      - minio-net

  webapp:
    build:
      context: ./webapps/nextjs
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_ZXhjaXRlZC1xdWFpbC00Ny5jbGVyay5hY2NvdW50cy5kZXYk
    container_name: webapp
    environment:
      PORT: 3022
      NODE_ENV: "production"
      API_VERSION: "v1"
      API_URL: "http://api:4022"
      API_AUTH_TOKEN: "2sOm7HFC5Yg6VaNb"
      CLERK_SECRET_KEY: "sk_test_YzoRlTSgsB1zFY4stTlbYX2AbTQIDaEj4vI5gVhtZM"

      NEXT_PUBLIC_STORAGE_PREFIX: "__minio"
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: "/sign-in"
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: "/sign-up"
      NEXT_PUBLIC_BASE_URL: "http://webapp:3022"
      NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: "/"
      NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: "/"
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_ZXhjaXRlZC1xdWFpbC00Ny5jbGVyay5hY2NvdW50cy5kZXYk"

    ports:
      - "3022:3022"
    depends_on:
      - api
    networks:
      - minio-net

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minio-net

  nginx:
    build:
      context: ./ssl
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - ./ssl/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/nginx/certs:/etc/nginx/certs
    ports:
      - "443:443"
    depends_on:
      - minio
    networks:
      - minio-net

volumes:
  minio_data:

networks:
  minio-net:
